spring:
  application:
    name:
      adapter
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:configserver:${CONFIG_SERVER:http://localhost:8889/}
  main:
    allow-bean-definition-overriding: true
server:
  port: 8088
springdoc:
  api-docs:
    path: /api-docs